import type { ScaffoldConfig } from '../../types/scaffold';

export function render(_config: ScaffoldConfig): string {
  return [
    "import { HttpRequest } from '@azure/functions';",
    "import { jwtVerify, importSPKI, type JWTPayload } from 'jose';",
    "import { env } from '../config/env';",
    '',
    'export interface AuthResult {',
    '  valid: boolean;',
    '  payload?: JWTPayload;',
    '  error?: string;',
    '}',
    '',
    '/**',
    ' * Validates JWT from the Authorization header of an Azure Functions request.',
    ' * Supports both symmetric (JWT_SECRET) and asymmetric (JWT_PUBLIC_KEY) keys.',
    ' */',
    'export async function verifyAuth(request: HttpRequest): Promise<AuthResult> {',
    "  const authHeader = request.headers.get('authorization');",
    "  if (!authHeader?.startsWith('Bearer ')) {",
    "    return { valid: false, error: 'Missing or invalid Authorization header' };",
    '  }',
    '',
    '  const token = authHeader.slice(7);',
    '',
    '  try {',
    '    let secret: Uint8Array | CryptoKey;',
    '',
    '    if (env.JWT_PUBLIC_KEY) {',
    "      secret = await importSPKI(env.JWT_PUBLIC_KEY, 'RS256');",
    '    } else if (env.JWT_SECRET) {',
    '      secret = new TextEncoder().encode(env.JWT_SECRET);',
    '    } else {',
    "      return { valid: false, error: 'No JWT_SECRET or JWT_PUBLIC_KEY configured' };",
    '    }',
    '',
    '    const { payload } = await jwtVerify(token, secret, {',
    '      issuer: env.JWT_ISSUER,',
    '      audience: env.JWT_AUDIENCE,',
    '    });',
    '',
    '    return { valid: true, payload };',
    '  } catch (err) {',
    '    // NEVER log the full token',
    "    console.error('[Auth] JWT verification failed:', (err as Error).message);",
    "    return { valid: false, error: 'Invalid or expired token' };",
    '  }',
    '}',
    '',
  ].join('\n');
}
