import type { ScaffoldConfig } from '../../types/scaffold';

export function render(_config: ScaffoldConfig): string {
	return [
		"import { app, HttpRequest, HttpResponseInit, InvocationContext } from '@azure/functions';",
		"import { getPool } from '../services/db';",
		'',
		'async function healthHandler(',
		'  request: HttpRequest,',
		'  context: InvocationContext,',
		'): Promise<HttpResponseInit> {',
		'  const result: Record<string, unknown> = {',
		"    status: 'ok',",
		'    timestamp: new Date().toISOString(),',
		'  };',
		'',
		'  try {',
		'    const pool = await getPool();',
		"    await pool.request().query('SELECT 1');",
		"    result.db = 'connected';",
		'  } catch (err) {',
		"    context.log('[Health] DB probe failed:', (err as Error).message);",
		"    result.status = 'degraded';",
		"    result.db = 'disconnected';",
		'  }',
		'',
		'  return {',
		'    jsonBody: result,',
		'  };',
		'}',
		'',
		"app.http('health', {",
		"  methods: ['GET'],",
		"  authLevel: 'anonymous',",
		'  handler: healthHandler,',
		'});',
		'',
	].join('\n');
}
