import type { ScaffoldConfig } from '../../types/scaffold';

export function render(_config: ScaffoldConfig): string {
  return [
    "import { app, HttpRequest, HttpResponseInit, InvocationContext } from '@azure/functions';",
    "import { z } from 'zod';",
    "import { verifyAuth } from '../middleware/authMiddleware';",
    "import { getPool } from '../services/db';",
    '',
    'const createItemSchema = z.object({',
    '  name: z.string().min(1).max(200),',
    '  description: z.string().max(1000).optional(),',
    '});',
    '',
    'async function apiHandler(',
    '  request: HttpRequest,',
    '  context: InvocationContext,',
    '): Promise<HttpResponseInit> {',
    '  // --- Authenticate ---',
    '  const auth = await verifyAuth(request);',
    '  if (!auth.valid) {',
    '    return { status: 401, jsonBody: { error: auth.error } };',
    '  }',
    '',
    '  try {',
    "    if (request.method === 'GET') {",
    '      const pool = await getPool();',
    "      const result = await pool.request().query('SELECT TOP 100 * FROM Items');",
    '      return { jsonBody: result.recordset };',
    '    }',
    '',
    "    if (request.method === 'POST') {",
    '      const body = await request.json();',
    '      const parsed = createItemSchema.safeParse(body);',
    '      if (!parsed.success) {',
    '        return {',
    '          status: 400,',
    '          jsonBody: { error: parsed.error.flatten().fieldErrors },',
    '        };',
    '      }',
    '',
    '      const pool = await getPool();',
    '      await pool',
    '        .request()',
    "        .input('name', parsed.data.name)",
    "        .input('description', parsed.data.description ?? null)",
    "        .query('INSERT INTO Items (Name, Description) VALUES (@name, @description)');",
    '',
    '      return { status: 201, jsonBody: { created: true } };',
    '    }',
    '',
    '    return { status: 405, jsonBody: { error: "Method not allowed" } };',
    '  } catch (err) {',
    "    context.error('[API] Unhandled error:', err);",
    '    // Generic message to client; details stay in logs',
    "    return { status: 500, jsonBody: { error: 'Internal server error' } };",
    '  }',
    '}',
    '',
    "app.http('api', {",
    "  methods: ['GET', 'POST'],",
    "  authLevel: 'function',",
    '  handler: apiHandler,',
    '});',
    '',
  ].join('\n');
}
