import type {ScaffoldConfig} from '../../types/scaffold';

/**
 * Generates the root CLAUDE.md with project overview and commands.
 */
export function renderRoot(config: ScaffoldConfig): string {
	const lines = [
		`# ${config.pluginName}`,
		``,
		`${config.description}`,
		``,
		`## Stack`,
		``,
		`- **Backend**: Express 4 + TypeScript + SQL Server (mssql)`,
		`- **Frontend**: ${config.includeFrontend ? 'Angular 16 + Module Federation' : 'Not included'}`,
		`- **Orchestration**: .NET Aspire (Node.js hosting)`,
		``,
		`## Build / Test / Lint Commands`,
		``,
		`### Root`,
		`- Install all: \`npm run install:all\``,
		`- Dev (Aspire): \`npm run dev\``,
		`- Build: \`npm run build\``,
		`- Start: \`npm run start\``,
		``,
		`### Backend (\`./backend\`)`,
		`- Dev: \`npm run dev\``,
		`- Build: \`npm run build\` (tsc)`,
		`- Start: \`npm start\``,
		``,
	];

	if (config.includeFrontend) {
		lines.push(
			`### Frontend (\`./frontend\`)`,
			`- Dev: \`npm start\` (ng serve with proxy)`,
			`- Build: \`npm run build\` (ng build --configuration production)`,
			`- Test: \`npm test\``,
			``,
		);
	}

	lines.push(
		`## Rules`,
		``,
		`See \`.claude/CLAUDE.md\` for the full MESAPPA on-prem development rules.`,
		``,
	);

	return lines.join('\n');
}

/**
 * Generates .claude/CLAUDE.md with full MESAPPA on-prem development rules.
 */
export function renderProject(config: ScaffoldConfig): string {
	return [
		`# MESAPPA On-Prem Plugin Development Rules`,
		``,
		`Project: **${config.pluginName}**`,
		``,
		`## Stack`,
		``,
		`- Angular 16 (frontend, if included)`,
		`- Express 4 with TypeScript (backend API)`,
		`- SQL Server (database, via mssql driver)`,
		`- .NET Aspire for local orchestration`,
		``,
		`## Repository Structure`,
		``,
		`\`\`\``,
		`${config.pluginName}/`,
		`  backend/          # Express API`,
		`    src/`,
		`      routes/       # Route handlers (thin layer)`,
		`      services/     # Business logic`,
		`      middleware/    # Auth, validation, error handling`,
		`      config/       # Environment & DB config`,
		`      server.ts     # Entry point`,
		`  frontend/         # Angular 16 app (optional)`,
		`    src/`,
		`      app/`,
		`        public-api/ # Minimal public-api surface`,
		`  scripts/          # PowerShell & Bash helpers`,
		`  docs/             # Documentation`,
		`  apphost.ts        # Aspire orchestrator`,
		`\`\`\``,
		``,
		`## Constraints`,
		``,
		`### V1 - On-Premise Only`,
		`No cloud-managed services. All infrastructure runs on-prem (Docker containers`,
		`or bare metal). No AWS/Azure/GCP SDK calls.`,
		``,
		`### V2 - SQL Server Only`,
		`Use SQL Server as the sole database. No ORM magic; use parameterized queries`,
		`via the \`mssql\` package. All queries must use \`sql.input()\` for parameters.`,
		``,
		`### V3 - Express Routes Are Thin`,
		`Route handlers call services. Business logic lives in \`services/\`, not in route`,
		`files. Routes handle request parsing, call the service, and return the response.`,
		``,
		`### V4 - CORS Whitelist`,
		`CORS origins are configured via \`CORS_ORIGIN\` env var. Never use \`origin: true\``,
		`or \`origin: '*'\` in production. Whitelist specific origins only.`,
		``,
		`### V5 - JWT Authentication`,
		`Use \`jose\` for JWT verification. Validate issuer, audience, and expiration.`,
		`Never decode without verification. Auth middleware protects all non-public routes.`,
		``,
		`### V6 - Helmet Security Headers`,
		`Always use \`helmet()\` middleware. Do not disable any default protections without`,
		`explicit justification in comments.`,
		``,
		`### V7 - Reproducible Builds`,
		`Use \`npm ci\` (not \`npm install\`) in CI/CD and deploy scripts. Requires a`,
		`committed \`package-lock.json\`. Angular builds use \`--configuration production\`.`,
		`Backend builds use \`tsc\`.`,
		``,
		`### V8 - No Hardcoded Paths`,
		`All file paths must be relative or derived from environment variables.`,
		`Never hardcode absolute paths in source code or scripts.`,
		``,
		`### V9 - Environment via .env`,
		`Use \`dotenv\` for local development. In production, environment variables are`,
		`injected by the deployment platform. Never commit \`.env\` files.`,
		``,
		`### V10 - Zod Validation`,
		`Validate all external inputs (request bodies, query params) with Zod schemas.`,
		`Define schemas next to the routes or services that use them.`,
		``,
		`### V11 - Error Handling`,
		`Use a centralized error-handling middleware. Return consistent error shapes:`,
		`\`{ error: string, details?: unknown }\`. Never leak stack traces in production.`,
		``,
		`## Security Rules`,
		``,
		`- All SQL queries MUST use parameterized inputs (\`sql.input()\`)`,
		`- Never concatenate user input into SQL strings`,
		`- JWT tokens must be verified on every protected request`,
		`- Secrets are never logged or returned in API responses`,
		`- Use HTTPS in production; configure TLS termination at the reverse proxy`,
		``,
		`## Frontend Rules`,
		``,
		`- Keep \`public-api\` surface minimal; export only what other modules consume`,
		`- Use Module Federation for micro-frontend integration`,
		`- Proxy API requests in development via \`proxy.conf.js\``,
		`- Lazy-load feature modules`,
		`- Do not import from \`@angular/http\`; use \`HttpClient\` from \`@angular/common/http\``,
		``,
		`## Backend Rules`,
		``,
		`- Routes are thin; services contain business logic (V3)`,
		`- CORS whitelist only; no wildcard origins (V4)`,
		`- All queries parameterized via \`mssql\` \`sql.input()\` (V2)`,
		`- Use \`helmet()\` defaults (V6)`,
		`- Validate inputs with Zod (V10)`,
		`- Centralized error handler (V11)`,
		``,
		`## Anti-Patterns to Block`,
		``,
		`- **No \`any\` types** - Use \`unknown\` and narrow, or define proper types`,
		`- **No string-concatenated SQL** - Always parameterize`,
		`- **No \`cors({ origin: true })\`** - Whitelist origins explicitly`,
		`- **No business logic in routes** - Extract to services`,
		`- **No \`npm install\` in CI** - Use \`npm ci\``,
		`- **No hardcoded absolute paths** - Use relative paths or env vars`,
		`- **No committed .env files** - Use .env.example as template`,
		`- **No cloud SDK imports** - On-prem only`,
		`- **No unvalidated request bodies** - Zod-validate everything`,
		`- **No disabled Helmet headers** - Keep defaults enabled`,
		``,
	].join('\n');
}
