import type {ScaffoldConfig} from '../../types/scaffold';

export function render(config: ScaffoldConfig): string {
	return [
		`# Environment Variables - ${config.pluginName}`,
		``,
		`## Database`,
		``,
		`| Variable | Description | Required | Example |`,
		`|----------|-------------|----------|---------|`,
		`| \`DB_HOST\` | SQL Server hostname | Yes | \`localhost\` |`,
		`| \`DB_PORT\` | SQL Server port | No (default: 1433) | \`1433\` |`,
		`| \`DB_USER\` | Database user | Yes | \`sa\` |`,
		`| \`DB_PASSWORD\` | Database password | Yes | \`YourStrong!Passw0rd\` |`,
		`| \`DB_NAME\` | Database name | Yes | \`plugindb\` |`,
		`| \`DATABASE_URL\` | Full connection string (overrides individual fields) | No | \`Server=localhost,1433;Database=plugindb;...\` |`,
		``,
		`## Authentication`,
		``,
		`| Variable | Description | Required | Example |`,
		`|----------|-------------|----------|---------|`,
		`| \`JWT_SECRET\` | Secret key for JWT signing/verification | Yes | \`a-random-256-bit-secret\` |`,
		`| \`JWT_ISSUER\` | Expected JWT issuer claim | Yes | \`https://mesa.example.com\` |`,
		`| \`JWT_AUDIENCE\` | Expected JWT audience claim | Yes | \`mesa-plugin\` |`,
		``,
		`## Server`,
		``,
		`| Variable | Description | Required | Example |`,
		`|----------|-------------|----------|---------|`,
		`| \`PORT\` | HTTP server port | No (default: 3000) | \`3000\` |`,
		`| \`NODE_ENV\` | Runtime environment | No (default: development) | \`production\` |`,
		``,
		`## CORS`,
		``,
		`| Variable | Description | Required | Example |`,
		`|----------|-------------|----------|---------|`,
		`| \`CORS_ORIGIN\` | Allowed origin(s), comma-separated | Yes | \`http://localhost:4200\` |`,
		``,
		`## Aspire (auto-injected)`,
		``,
		`These variables are automatically injected by the Aspire host at runtime.`,
		`You do **not** need to set them manually.`,
		``,
		`| Variable | Description | Required | Example |`,
		`|----------|-------------|----------|---------|`,
		`| \`ASPIRE_SERVICE_NAME\` | Logical service name in the Aspire app model | No (auto) | \`api\` |`,
		`| \`OTEL_EXPORTER_OTLP_ENDPOINT\` | OpenTelemetry collector endpoint | No (auto) | \`http://localhost:4317\` |`,
		``,
	].join('\n');
}
