import type { PrototypeConfig } from '../../../generators/prototype-scaffold';

export function render(config: PrototypeConfig): string {
  return `# ${config.name}

${config.description}

Generated by **mesa prototype** — a Vercel + Next.js + Hono + Neon Postgres monorepo
with Vercel Blob storage and username/password authentication.

## Stack

| Layer    | Technology                                  |
| -------- | ------------------------------------------- |
| Frontend | Next.js 15 (App Router) + Tailwind v4       |
| Backend  | Hono (mounted on Next.js \`api/[...route]\`) |
| Database | Neon Postgres (\`@neondatabase/serverless\`) |
| ORM      | Drizzle ORM                                 |
| Storage  | Vercel Blob (\`@vercel/blob\`)               |
| Auth     | Username + password (bcryptjs) + JWT (jose) |
| Deploy   | Vercel + GitHub Actions (manual only)       |

## Repository layout

\`\`\`
${config.name}/
  apps/
    web/                    # Next.js (App Router) — also hosts the Hono API
      src/app/api/[...route]/route.ts   # Hono mounted as catch-all
    api/                    # Hono app + routes (importable from web)
      src/
        app.ts              # Hono app builder
        routes/             # auth, health, uploads
        middleware/auth.ts  # JWT verifier
        lib/storage.ts      # Vercel Blob helpers
        env.ts              # Zod-validated env
  packages/
    db/                     # Drizzle schema + Neon client
      src/schema.ts
      src/client.ts
      drizzle.config.ts
  vercel.json
  .github/workflows/
    ci.yml                  # Lint + build on push/PR (no deploy)
    deploy.yml              # Manual deploy via workflow_dispatch
  .cursor/rules/            # Web-architecture, security, testing rules
  .claude/skills/           # Architecture audit, REST design, secrets, deployment
\`\`\`

## Quick start

\`\`\`bash
pnpm install
cp .env.example .env.local
# Fill NEON_DATABASE_URL, JWT_SECRET, BLOB_READ_WRITE_TOKEN

pnpm db:push                # Push Drizzle schema to Neon
pnpm dev                    # http://localhost:3000
\`\`\`

### Auth flow

\`\`\`bash
# Register
curl -X POST http://localhost:3000/api/auth/register \\
  -H 'content-type: application/json' \\
  -d '{"username":"alice","password":"correct horse battery staple"}'

# Login (returns JWT)
curl -X POST http://localhost:3000/api/auth/login \\
  -H 'content-type: application/json' \\
  -d '{"username":"alice","password":"correct horse battery staple"}'

# Authenticated request
curl http://localhost:3000/api/me -H "Authorization: Bearer <jwt>"
\`\`\`

## Deployment

This project ships with **manual-only** deploys. CI runs lint + build on every push/PR
but never auto-deploys.

\`\`\`bash
vercel link                                              # First time only
vercel env add NEON_DATABASE_URL preview production      # Set secrets per environment
vercel env add JWT_SECRET preview production
vercel env add BLOB_READ_WRITE_TOKEN preview production
\`\`\`

Then trigger from GitHub:

\`\`\`bash
gh workflow run deploy.yml -f environment=preview
gh workflow run deploy.yml -f environment=production
\`\`\`

Both \`preview\` and \`production\` are declared as GitHub environments in
\`.github/workflows/deploy.yml\` so you can wire up required reviewers and
environment-scoped secrets in the GitHub UI.

## Verify the architecture

\`\`\`bash
mesa verify                  # Run all checks against the project
mesa verify --explain        # Show evidence per check
mesa verify --json           # Machine-readable output
\`\`\`

## Rules and skills

- \`.cursor/rules/web-architecture.mdc\`
- \`.cursor/rules/security.mdc\`
- \`.cursor/rules/testing.mdc\`
- \`.claude/skills/architecture-audit.md\`
- \`.claude/skills/rest-api-design.md\`
- \`.claude/skills/secrets-management.md\`
- \`.claude/skills/vercel-neon-deployment.md\`
`;
}
