import type { ScaffoldConfig } from '../../types/scaffold';

export function render(_config: ScaffoldConfig): string {
  return [
    `# start-local.ps1 - Start the local development environment`,
    `# Usage: .\\scripts\\start-local.ps1`,
    ``,
    `$ErrorActionPreference = "Stop"`,
    `$scriptDir = $PSScriptRoot`,
    `$projectRoot = Split-Path -Parent $scriptDir`,
    ``,
    `Write-Host "=== Starting local development environment ===" -ForegroundColor Cyan`,
    ``,
    `# Check Docker is running`,
    `try {`,
    `    docker info | Out-Null`,
    `    Write-Host "[OK] Docker is running" -ForegroundColor Green`,
    `} catch {`,
    `    Write-Host "[ERROR] Docker is not running. Please start Docker Desktop." -ForegroundColor Red`,
    `    exit 1`,
    `}`,
    ``,
    `# Check Aspire CLI is installed`,
    `$aspireAvailable = $false`,
    `try {`,
    `    aspire --version | Out-Null`,
    `    $aspireAvailable = $true`,
    `    Write-Host "[OK] Aspire CLI is installed" -ForegroundColor Green`,
    `} catch {`,
    `    Write-Host "[WARN] Aspire CLI not found." -ForegroundColor Yellow`,
    `}`,
    ``,
    `if ($aspireAvailable) {`,
    `    Write-Host "Starting with Aspire..." -ForegroundColor Cyan`,
    `    Set-Location $projectRoot`,
    `    aspire run`,
    `} else {`,
    `    Write-Host ""`,
    `    Write-Host "Aspire CLI is not installed. To install it:" -ForegroundColor Yellow`,
    `    Write-Host "  irm https://aspire.dev/install.ps1 | iex" -ForegroundColor White`,
    `    Write-Host ""`,
    `    Write-Host "Alternatively, start services manually:" -ForegroundColor Yellow`,
    `    Write-Host "  1. Start SQL Server via Docker:" -ForegroundColor White`,
    `    Write-Host "     docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=YourStrong!Passw0rd -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest" -ForegroundColor White`,
    `    Write-Host "  2. Copy .env.example to .env and configure database credentials" -ForegroundColor White`,
    `    Write-Host "  3. Start backend: cd backend && npm run dev" -ForegroundColor White`,
    `    Write-Host "  4. Start frontend: cd frontend && npm start" -ForegroundColor White`,
    `    exit 1`,
    `}`,
    ``,
  ].join('\n');
}
