import type {ScaffoldConfig} from '../../types/scaffold';

export function render(_config: ScaffoldConfig): string {
	return [
		`#!/usr/bin/env bash`,
		`# start-local.sh - Start the local development environment`,
		`# Usage: ./scripts/start-local.sh`,
		``,
		`set -euo pipefail`,
		``,
		`SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"`,
		`PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"`,
		``,
		`echo "=== Starting local development environment ==="`,
		``,
		`# Check Docker is running`,
		`if ! docker info > /dev/null 2>&1; then`,
		`  echo "[ERROR] Docker is not running. Please start Docker Desktop."`,
		`  exit 1`,
		`fi`,
		`echo "[OK] Docker is running"`,
		``,
		`# Check Aspire CLI is installed`,
		`ASPIRE_AVAILABLE=false`,
		`if command -v aspire > /dev/null 2>&1; then`,
		`  ASPIRE_AVAILABLE=true`,
		`  echo "[OK] Aspire CLI is installed"`,
		`else`,
		`  echo "[WARN] Aspire CLI not found."`,
		`fi`,
		``,
		`if [ "$ASPIRE_AVAILABLE" = true ]; then`,
		`  echo "Starting with Aspire..."`,
		`  cd "$PROJECT_ROOT"`,
		`  aspire run`,
		`else`,
		`  echo ""`,
		`  echo "Aspire CLI is not installed. To install it:"`,
		`  echo "  curl -sSL https://aspire.dev/install.sh | bash"`,
		`  echo ""`,
		`  echo "Alternatively, start services manually:"`,
		`  echo "  1. Start SQL Server via Docker:"`,
		`  echo "     docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=YourStrong!Passw0rd -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest"`,
		`  echo "  2. Copy .env.example to .env and configure database credentials"`,
		`  echo "  3. Start backend: cd backend && npm run dev"`,
		`  echo "  4. Start frontend: cd frontend && npm start"`,
		`  exit 1`,
		`fi`,
		``,
	].join('\n');
}
